# Languaje de la aplicación
language: node_js

# Versiones con las que correr los tests
node_js:
  - stable
  - 6.1.0
  - 5.5.0
  - 4.4.3
  - 4.2.6

sudo: false

script:
  - npm test

after_success:
        - npm run coveralls
